name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # ---------------------------------------------------------
      # PARTE 1: GERA APENAS AS LINGUAGENS (languages.svg)
      # ---------------------------------------------------------
      - name: 1. Linguagens
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: languages.svg
          user: Viniirb
          base: "" # Sem cabeçalho
          config_timezone: America/Sao_Paulo
          
          # Apenas Plugin de Linguagens Ativo
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_details: percentage
          
          # Desativar outros plugins nesta etapa
          plugin_steam: no
          plugin_music: no

      # ---------------------------------------------------------
      # PARTE 2: GERA APENAS OS HOBBIES (hobbies.svg)
      # ---------------------------------------------------------
      - name: 2. Hobbies (Steam + Spotify)
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          filename: hobbies.svg
          user: Viniirb
          base: "" # Sem cabeçalho
          config_timezone: America/Sao_Paulo
          
          # Desativar linguagens nesta etapa
          plugin_languages: no
          
          # Plugin: Steam
          plugin_steam: yes
          plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          plugin_steam_user: "76561198304084021"
          plugin_steam_sections: player, most-played
          plugin_steam_achievements_limit: 0
          
          # Plugin: Spotify
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_limit: 4
          plugin_music_mode: top
