name: Metrics
on:
  # Agenda atualizações diárias
  schedule: [{cron: "0 0 * * *"}]
  # Permite rodar manualmente na aba Actions
  workflow_dispatch:
  # Roda a cada push na main
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Token do GitHub (Configure nos Secrets do Repo como METRICS_TOKEN)
          token: ${{ secrets.METRICS_TOKEN }}

          # Configurações Básicas
          user: Viniirb
          template: classic
          base: "" # Deixa vazio para não mostrar o header padrão (você já tem um)
          config_timezone: America/Sao_Paulo
          filename: github-metrics.svg
          
          # Plugin: Linguagens
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css
          plugin_languages_limit: 6
          plugin_languages_sections: most-used
          plugin_languages_colors: "github"
          plugin_languages_details: percentage
          
          # Plugin: Steam 
          # Configure o segredo STEAM_TOKEN e troque o ID abaixo
          # plugin_steam: yes
          # plugin_steam_token: ${{ secrets.STEAM_TOKEN }}
          # plugin_steam_user: "SEU_ID_NUMERICO_DA_STEAM_AQUI" 
          # plugin_steam_sections: player, most-played
          # plugin_steam_achievements_limit: 0
          
          # Plugin: Spotify
          # Configure o segredo SPOTIFY_CLIENT_ID, SPOTIFY_CLIENT_SECRET, SPOTIFY_REFRESH_TOKEN
          plugin_music: yes
          plugin_music_provider: spotify
          plugin_music_token: "${{ secrets.SPOTIFY_CLIENT_ID }}, ${{ secrets.SPOTIFY_CLIENT_SECRET }}, ${{ secrets.SPOTIFY_REFRESH_TOKEN }}"
          plugin_music_limit: 4
          plugin_music_mode: top
